[package]
name = "fog05-zservice-macros"
version = "0.3.0"
repository = "https://github.com/eclipse-fog05/fog05"
homepage = "http://fog05.io"
authors = ["gabrik <gabriele.baldoni@gmail.com>"]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
description = "fog05: The End-to-End Compute, Storage and Networking Virtualisation solution."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# To build with debug on macros: RUSTFLAGS="-Z macro-backtrace"

[dependencies]
hex = "0.4.2"
futures = "0.3.5"
syn = { version = "1.0.11", features = ["full"] }
quote = "1.0.2"
proc-macro2 = "1.0.6"
serde_derive = "1.0.55"
serde = { version = "1.0.55", features = ["derive"] }
serde_json = "1.0.55"
bincode = "1.3.1"
zenoh = "0.5.0-beta.3"
fog05-zservice = {path = "../fog05-zservice"}
async-trait = "0.1.41"
base64 = "0.12.3"
log = "0.4.11"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
darling = "0.10.2"

[dependencies.async-std]
version = "~1.6.4"
features = ["attributes"]


[lib]
proc-macro = true


[[example]]
name = "zworking"


[[example]]
name = "zservice"