FROM alpine:3.12

LABEL maintainer="Gabriele Baldoni <gabriele.baldoni@adlinktech.com>"

RUN apk add --no-cache \
        libc6-compat curl


RUN curl https://github.com/eclipse-fog05/fog05/releases/download/v0.2.1/libzenohc-amd64.so -L -o /usr/local/lib/libzenohc.so
COPY force /root/force

EXPOSE 9191

ENTRYPOINT ["/root/force"]